// <auto-generated />
using System;
using Laundry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Laundry.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200227221023_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Laundry.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Laundry.Models.WashingMachine", b =>
                {
                    b.Property<int>("WashingMachineId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Duration");

                    b.Property<int>("DurationLeft");

                    b.Property<string>("ModelName")
                        .IsRequired();

                    b.Property<string>("PicURL")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<DateTime>("UsedAt");

                    b.Property<int>("UserId");

                    b.Property<string>("status");

                    b.HasKey("WashingMachineId");

                    b.HasIndex("UserId");

                    b.ToTable("WashingMachines");
                });

            modelBuilder.Entity("Laundry.Models.WashingMachine", b =>
                {
                    b.HasOne("Laundry.Models.User", "UserOccupied")
                        .WithMany("WashingMachinesInUse")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
